targets:
  $default:
    builders:
      deserialization_generator|deserializationGenerator:
        enabled: true
      api_call_generator|apiGenerator:
        enabled: true

builders:
  deserialization_generator|deserializationGenerator:
    target: ":deserialization_generator"
    import: "package:trireme_client/tool/deserialization_generator.dart"
    builder_factories: ["deserializationGenerator"]
    build_extensions: {".dart": ["deserialize.g.part"]}
    build_to: "cache"
    applies_builders: ["source_gen|combining_builder"]
  api_call_generator|apiGenerator:
    target: ":api_call_generator"
    import: "package:trireme_client/tool/api_call_generator.dart"
    builder_factories: ["apiGenerator"]
    build_extensions: {".dart": ["apis.g.part"]}
    build_to: "cache"
    applies_builders: ["source_gen|combining_builder"]
