name: trireme_client
description: Deluge client written in Dart
version: 0.0.1
homepage: https://github.com/teal77/trireme_client

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  rencode: "0.0.5"

dev_dependencies:
  test: "^1.24.6"
  build_runner: "^2.4.6"
  source_gen: "^1.3.2"
  lints: "^2.1.1"