name: trireme_client
description: Deluge client written in Dart
version: 0.0.1
homepage: https://github.com/teal77/trireme_client

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  rencode: "0.0.4"
  type_helper: "^0.1.0"

dev_dependencies:
  test: "^1.16.8"
  build_runner: "^1.12.1"
  source_gen: "^0.9.10+4"
  pedantic: "^1.11.0"