name: trireme_client
description: Deluge client written in Dart
version: 0.0.1
author:
homepage:

dependencies:
  rencode: "0.0.3"

dev_dependencies:
  test: "^1.2.0"
  build_runner: "^0.10.2"
  source_gen: "^0.8.3"