name: trireme_client
description: Deluge client written in Dart
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  rencode: "0.0.3"

dev_dependencies:
  test: "^1.5.1"
  build_runner: "^0.10.2"
  source_gen: "^0.9.1"